public class ApexDataTypeDemo1 {
    
    public static void method1(){
        Boolean isActive = true;
        System.debug('Value of isActive ='+ isActive);
    }
    public static void method2(){
        String fname='Mubarak',lname='Husain';
        System.debug('Name = '+ fname + ' '+lname);
    }
    public static void method3(){
        ID accId ='001J200000BieU9IAJ';
        System.debug('ID ='+ accId);
    }

}