public class TaskUtil {
    public static String getTaskPriority(String leadState){
        //Validate Input
        if(String.isBlank(leadState)|| leadState.length()>2){
            return null;
        }
        
        string taskPriority;
        if (leadState == 'CA'){
            taskPriority ='High';
        }else {
            taskPriority = 'Normal';
        }
        return taskPriority;
    }
}